### ISSUE TITLE
OnScreensize returns extralarge on android emulator

### ISSUE THREAD

**Issue by gabsamples6** [carolzbnbr/OnScreenSizeMarkup#10]
Hi
I really like this nuget package and this is what we really need , I have a problem in a maui app I am building
I have 2 emulators set up as follows - notice size see  pic below - 
Despite what I do to set the font size it always detected it as extra large. Am I missing something?

`     <Label
         Grid.Row="2"
         FontSize="{maui:OnScreenSize ExtraLarge=80,
                                      Large=28,
                                      Default=18,
                                      Medium=12,
                                      Small=8,
                                      ExtraSmall=6}"
         Text="Sample Text using OnScreenSize" />`

![image](https://user-images.githubusercontent.com/109357537/215841876-79abb1c3-e926-47f7-9aeb-163a6ebed54c.png)

1. Just run your solution
2.  removed everything 
3.  updated to .net 7 
4. Referenced your 2.1.2 nuget

![image](https://user-images.githubusercontent.com/109357537/215848014-94839a37-77bc-4839-ae64-fba983ca8501.png)

Any suggestions?

**Comment by carolzbnbr** [comment]
Sorry, I closed the Issue by mistake :)

**Comment by gabsamples6** [comment]
Hi -
Extremely grateful for your time and detailed answer, I love this nuget and I do hope it makes it in the community toolkit.
Your solution worked see pic below, however I was truly puzzled by the output in the output windows (I am using win 11)

**On android 13 i get below**

`[DOTNET] ** DEBUG ** OnScreenSizeMarkup (OnScreenSizeHelper.shared.GetScreenDiagonalInches): OnScreenSizeExtension - DiagonalSize: 16.1,  PPI/DPI: x:"160", y:"160"
`
**Fix**
   `OnScreenSizeMarkup.Maui.Manager.Current.Mappings.Add(new SizeMappingInfo(16.1, ScreenCategories.Large, ScreenSizeCompareModes.SpecificSize));`

![image](https://user-images.githubusercontent.com/109357537/216123517-73747e1b-2aaf-4b0f-83b0-3578283b0902.png)


**On android 11 i get below**

`[DOTNET] ** DEBUG ** OnScreenSizeMarkup (OnScreenSizeHelper.shared.GetScreenDiagonalInches): OnScreenSizeExtension - DiagonalSize: 5.9,  PPI/DPI: x:"440", y:"440"`

![image](https://user-images.githubusercontent.com/109357537/216126701-078eecda-9163-49e8-9740-25d21819b387.png)

![image](https://user-images.githubusercontent.com/109357537/216126741-193de8b5-d653-46af-abaf-3e1294acbaa9.png)


Do you know if happens to real devices too? 
What happens for argument sake if you have a device that is truly 16.1 and that it will apply our custom mapping?

Interestingly this only happes on android 13.

Not sure how to best approach this - but considering that the app is mobile only, I guess is safe to mark that as large, and If I understood it correctly - you consider extraLarge tablets etc.. but not actual phones..

Again
thanks for your help and if you have any other suggestions please let know.

**Comment by carolzbnbr** [comment]
Glad it worked! 

About your latest questions:

`Do you know if happens to real devices too?`

 I can't tell you if that behaviour occurs on real Android devices, I do not have any real device with me (only IPhones). If you don't feel confident, I would recommend you to use real device testing platforms such as Browserstack.

`What happens for argument sake if you have a device that is truly 16.1 and that it will apply our custom mapping?`

The most problems occurs on the latest version of Android, for some reason the DisplayMetrics returns wrong information for XDPI and YDPI on latest version. I haven't have time to investigate this API and even evaluate other options so we could safely replace that API for anything else, but if someone could help me on it, that would be very helpful for the Markup and community.

So I would recommend you to add an If statement on the Reamp, checking if user is using Android 13, and if that is the case, you can use the remap. 

'Not sure how to best approach this - but considering that the app is mobile only, I guess is safe to mark that as large, and If I understood it correctly - you consider extraLarge tablets etc.. but not actual phones..'

Yes, you are right, we consider extra large for tablets. 

if you want, you can fully override these settings (Mappings) with your own:

```cs
          OnScreenSizeMarkup.Maui.Manager.Current.Mappings = new List<SizeMappingInfo>
            {
                new SizeMappingInfo(4.9, ScreenCategories.Small, ScreenSizeCompareModes.SmallerOrEqualsTo),
                new SizeMappingInfo(6.2, ScreenCategories.Medium, ScreenSizeCompareModes.SmallerOrEqualsTo),
                new SizeMappingInfo(200.0, ScreenCategories.Large, ScreenSizeCompareModes.SmallerOrEqualsTo),
            };

```

The example below is a fallback.

So, lets take the line `new SizeMappingInfo(200.0, ScreenCategories.Large, ScreenSizeCompareModes.SmallerOrEqualsTo),` as an example:

On that line we are telling the Markup engine that any DiagonalSize smaller or equals to 200 should be classified as Large.

The some thing happens for the other two lines.

So what I would do if I were you, to kind of "solve" this issue is adding a couple of If statements checking if user is running on Android, and if it is Android 13, Remap using *ScreenSizeCompareModes.SpecificSize* as my previous reply, otherwise remap according to the example I gave you using the  'ScreenSizeCompareModes.SmallerOrEqualsTo'.

If you want you can mix both *ScreenSizeCompareModes.SmallerOrEqualsTo* and *ScreenSizeCompareModes.SpecificSize*.

Also, if you want to replace the entire categorization logic, you can implement *IScreenCategorizer* interface, and set its instance on the App.cs like this:

```cs
OnScreenSizeMarkup.Maui.Manager.Current.Categorizer = new MyOwnIScreenCategorizer();
```

By doing this, you can totally replace the android/ios logic to categorize screens.

Cheers

**Comment by gabsamples6** [comment]
Hi Brilliant - again thanks for your details answer- you have given me much info to have a workable workround. I dont even know where you log bugs with them and not even sure if they are fixing them... because it would be worth raising an issue..

Thanks for your support and providing this
